name: Deploy to Cloudflare

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-node-and-dependencies

      - name: Run linter
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-node-and-dependencies

      - name: Run unit tests
        run: npm run test:unit

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-node-and-dependencies

      - name: Build
        run: npm run build
        env:
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DEPLOY_TO_CF: "true"

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages deploy dist --project-name=10xdev
          ls -la ./dist/_astro/
          CHUNK_FILE=$(find ./chunks -name "supabase.client_*.mjs")
          echo "Found Supabase client chunk at: $CHUNK_FILE"
          cat "$CHUNK_FILE"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
